version: 2
jobs:
    build-and-test:
        working_directory: ~/willitrain

        docker:
            - image: circleci/python:3.6.8

        steps:
            - checkout

            - restore_cache:
                keys:
                    - deps-{{ checksum "poetry.lock" }}

            - run:
                name: Install Dependencies
                command: poetry install

            - save_cache:
                key: deps-{{ checksum "poetry.lock" }}
                paths:
                    - /home/circleci/.cache/pypoetry/virtualenvs
            - run:
                name: Run Tests
                command: |
                    echo 'export CI="circleci"' >> $BASH_ENV
                    ./run_format_check.sh
                    ./run_tests.sh

workflows:
    version: 2
    build-and-test-workflow:
        jobs:
            - build-and-test
